version: "2"

services:
  unity:
    build: .
    tty: true
    env_file:
      - .env
    volumes:
      - ./context:/context
    networks:
      unity_net:
        ipv4_address: 172.16.250.10
    container_name: unity-service
networks:
  unity_net:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "true"
    ipam:
      driver: default
      config:
      - subnet: 172.16.250.0/24
        gateway: 172.16.250.1